# Generated by Django 6.1.1 on 2026-10-05 00:07

import django.db.models.deletion
import fiscal_app.models.software_registration
import fiscal_app.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('key_id', fiscal_app.utils.fields.ExactCharField(max_length=40, unique=True)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', fiscal_app.utils.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='fiscal_app.clientsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', fiscal_app.utils.fields.ExactCharField(max_length=120)),
                ('kind', models.CharField(choices=[('invoice', 'Factura electrónica de venta'), ('credit_note', 'Nota crédito'), ('debit_note', 'Nota débito')], max_length=11)),
                ('prefix', models.CharField(blank=True, default='', max_length=4)),
                ('number', models.PositiveBigIntegerField()),
                ('issue_datetime', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('queued', 'En cola'), ('transmitting', 'Transmitiendo'), ('validated', 'Validado por la DIAN'), ('rejected', 'Rechazado por la DIAN'), ('contingency_dian', 'Contingencia por falla de la DIAN (tipo 04)'), ('contingency_issuer', 'Contingencia del emisor (tipo 03)')], default='queued', max_length=18)),
                ('cufe', models.CharField(blank=True, default='', max_length=96)),
                ('qr_url', models.URLField(blank=True, default='', max_length=500)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fiscal_app.clientsystem')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='fiscal_app.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('signed_xml', 'XML firmado'), ('dian_response', 'Respuesta de la DIAN (ApplicationResponse)'), ('attached_document', 'AttachedDocument'), ('pdf', 'Representación gráfica (PDF)'), ('evidence', 'Evidencia de contingencia')], max_length=17)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('storage_path', models.CharField(max_length=500)),
                ('retain_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='fiscal_app.document')),
            ],
            options={
                'ordering': ['document', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('queued', 'En cola'), ('transmitting', 'Transmitiendo'), ('validated', 'Validado por la DIAN'), ('rejected', 'Rechazado por la DIAN'), ('contingency_dian', 'Contingencia por falla de la DIAN (tipo 04)'), ('contingency_issuer', 'Contingencia del emisor (tipo 03)')], max_length=18)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fiscal_app.document')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15)),
                ('dv', models.CharField(max_length=1)),
                ('person_type', models.CharField(choices=[('1', 'Persona jurídica'), ('2', 'Persona natural')], max_length=1)),
                ('legal_name', models.CharField(max_length=450)),
                ('trade_name', models.CharField(blank=True, default='', max_length=450)),
                ('tax_responsibilities', models.JSONField(blank=True, default=list)),
                ('tax_scheme', models.CharField(default='01', max_length=2)),
                ('address_line', models.CharField(max_length=300)),
                ('municipality_code', models.CharField(help_text='Código DANE del municipio (5 dígitos)', max_length=5)),
                ('department_code', models.CharField(help_text='Código DANE del departamento (2 dígitos)', max_length=2)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('country_code', models.CharField(default='CO', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('environment', models.CharField(choices=[('1', 'Producción'), ('2', 'Pruebas')], default='2', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuers', to='fiscal_app.clientsystem')),
            ],
            options={
                'ordering': ['legal_name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fiscal_app.issuer'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p12', fiscal_app.utils.fields.EncryptedTextField()),
                ('password', fiscal_app.utils.fields.EncryptedTextField()),
                ('subject', models.CharField(max_length=500)),
                ('issued_by', models.CharField(max_length=500)),
                ('serial', models.CharField(max_length=80)),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='fiscal_app.issuer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumberingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoice', 'Facturación'), ('contingency', 'Contingencia (papel o talonario)')], default='invoice', max_length=11)),
                ('resolution_number', models.CharField(max_length=30)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, default='', max_length=4)),
                ('number_from', models.PositiveBigIntegerField()),
                ('number_to', models.PositiveBigIntegerField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('technical_key', fiscal_app.utils.fields.EncryptedTextField(blank=True, default='')),
                ('establishment', models.CharField(blank=True, default='', help_text='Local o punto de venta', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbering_ranges', to='fiscal_app.issuer')),
            ],
            options={
                'ordering': ['issuer', 'prefix', 'number_from'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='numbering_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fiscal_app.numberingrange'),
        ),
        migrations.CreateModel(
            name='SoftwareRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('1', 'Producción'), ('2', 'Pruebas')], max_length=1)),
                ('software_id', models.CharField(max_length=80)),
                ('software_pin', fiscal_app.utils.fields.EncryptedTextField()),
                ('test_set_id', models.CharField(blank=True, default='', max_length=80)),
                ('manufacturer_nit', models.CharField(default=fiscal_app.models.software_registration.default_manufacturer_nit, max_length=15)),
                ('manufacturer_name', models.CharField(default=fiscal_app.models.software_registration.default_manufacturer_name, max_length=200)),
                ('software_name', models.CharField(default=fiscal_app.models.software_registration.default_software_name, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_registrations', to='fiscal_app.issuer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='fiscal_app.clientsystem')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_deliveries', to='fiscal_app.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='issuer',
            constraint=models.UniqueConstraint(fields=('client', 'nit'), name='issuer_unique_nit_per_client'),
        ),
        migrations.AddConstraint(
            model_name='numberingrange',
            constraint=models.UniqueConstraint(fields=('issuer', 'resolution_number', 'prefix'), name='range_unique_resolution_prefix'),
        ),
        migrations.AddConstraint(
            model_name='numberingrange',
            constraint=models.CheckConstraint(condition=models.Q(('number_from__lte', models.F('number_to'))), name='range_numbers_ordered'),
        ),
        migrations.AddConstraint(
            model_name='numberingrange',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__lte', models.F('valid_to'))), name='range_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['state', 'next_attempt_at'], name='document_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('client', 'idempotency_key'), name='document_unique_key_per_client'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('issuer', 'kind', 'prefix', 'number'), name='document_unique_number_per_issuer'),
        ),
        migrations.AddConstraint(
            model_name='softwareregistration',
            constraint=models.UniqueConstraint(fields=('issuer', 'environment', 'software_id'), name='software_unique_per_issuer_environment'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['delivered_at', 'next_attempt_at'], name='webhook_pending_idx'),
        ),
    ]
