# Generated by Django 6.1.1 on 2026-10-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_app', '0002_fiscal_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='transient_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
