# Generated by Django 6.1.1 on 2026-10-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_app', '0003_document_transient_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='dian_file_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuer',
            name='dian_file_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
