# Generated by Django 6.1.1 on 2026-10-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_app', '0004_issuer_dian_file_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contingency_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='invoice_type',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
