# Generated by Django 6.1.1 on 2026-10-05 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_app', '0005_document_invoice_type_contingency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('beat_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_deliveries', to='fiscal_app.document'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('certificate_expiring', 'Certificado por vencer'), ('range_low', 'Numeración por agotarse'), ('resolution_expiring', 'Resolución de numeración por vencer'), ('contingency_deadline', 'Plazo de contingencia'), ('rejection', 'Rechazo de la DIAN'), ('queue_stuck', 'Cola detenida')], max_length=24)),
                ('severity', models.CharField(choices=[('warning', 'Advertencia'), ('critical', 'Crítica')], default='warning', max_length=8)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fiscal_app.document')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fiscal_app.issuer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved_at', 'created_at'], name='alert_open_idx')],
            },
        ),
    ]
