# Generated by Django 6.1.1 on 2026-10-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_app', '0006_alerts_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSetRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_set_id', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('processing', 'En proceso en la DIAN'), ('accepted', 'Aceptado'), ('rejected', 'Con rechazos'), ('failed', 'No se pudo enviar')], default='processing', max_length=10)),
                ('entries', models.JSONField(default=list)),
                ('phases', models.JSONField(default=list)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_set_runs', to='fiscal_app.issuer')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
